UserApplication/Controllers/TintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserApplication.Models;
using UserApplication.ViewModel;


namespace UserApplication.Controllers
{
    public class TintController : Controller
    {
        // GET: Tint
        public ActionResult Home()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Home(TintVM tintVM)
        {
            TintVM temp = tintVM;

            List<string> ValidationList = new List<string>();

           

                ApplicationDbContext dbContext = new ApplicationDbContext();
                if (tintVM != null)
                {
                    if (tintVM.Person != null)
                    {
                        var Person = dbContext.Persons.Add(tintVM.Person);
                        dbContext.SaveChanges();


                        if (Person?.PersonId > 0)
                        {
                            if (tintVM.Vehicle != null)
                            {
                                tintVM.Vehicle.PersonId = Person.PersonId;
                                dbContext.Vehicles.Add(tintVM.Vehicle);
                            }
                            if (tintVM.SelfEmployed != null)
                            {
                                tintVM.SelfEmployed.PersonId = Person.PersonId;
                                dbContext.selfEmployeds.Add(tintVM.SelfEmployed);
                            }
                            if (tintVM.Employer != null)
                            {
                                tintVM.Employer.PersonId = Person.PersonId;
                                dbContext.Employers.Add(tintVM.Employer);
                            }
                            if (tintVM.MartialStatus != null)
                            {
                                tintVM.MartialStatus.PersonId = Person.PersonId;
                                dbContext.MartialStatuses.Add(tintVM.MartialStatus);
                            }
                            if (tintVM.Citizen != null)
                            {
                                tintVM.Citizen.PersonId = Person.PersonId;
                                dbContext.Citizens.Add(tintVM.Citizen);
                            }
                            if (tintVM.ImmigrationStatus != null)
                            {
                                tintVM.ImmigrationStatus.PersonId = Person.PersonId;
                                dbContext.ImmigrationStatuses.Add(tintVM.ImmigrationStatus);
                            }
                            
                            if (tintVM.Applicant != null)
                            {
                                if (string.IsNullOrEmpty(tintVM.Applicant.FormNumber))
                                {
                                    ValidationList.Add("Please provide form number");
                                }
                                if (tintVM.Applicant.DateOfApplication == null)
                                {
                                    ValidationList.Add("Please provide Date of Application");
                                }
                                if (tintVM.Person.PersonId == 0)
                                {
                                    ValidationList.Add("Form Person not created successfully.");
                                }

                                tintVM.Applicant.PersonId = Person.PersonId;
                                dbContext.Applicants.Add(tintVM.Applicant);
                                dbContext.SaveChanges();
                        }
                        }
                        else
                        {
                            ValidationList.Add("Form Person not created successfully. Retry");
                        }

                    }
                }

            if (ValidationList?.Count > 0)
            {
                foreach (var item in ValidationList)
                {
                    ModelState.AddModelError(string.Empty, item);
                }
                return View(tintVM);
            }


            return View(tintVM);
        }
    }
}

UserApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Advance User Managment</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!--Extra test-->
    @*@Styles.Render("~/css/NewStyles/style.css")*@
    @Styles.Render("~/css/NewStyles/StyleSheet1.css")
    <!--Exta test-->



</head>
<body>
    <div class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span style="color: #fff;" class="glyphicon glyphicon-align-justify"></span>
                </button>
                @Html.ActionLink("USerApplication", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("TintForm", "Home", "Tint")</li>
                    <li>@Html.ActionLink("TintNew", "HomeNew", "TintNewForm")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <!--Extra-->
    @*@Scripts.Render("~/js/NewJs/jquer-3.3.1.min.js")
    @Scripts.Render("~/js/NewJs/jquery.steps.js")
    @Scripts.Render("~/js/NewJs/main.js"*@)
    @Scripts.Render("~/js/NewJs/JavaScript1.js")

    <!--Extra-->


    @RenderSection("scripts", required: false)



</body>

<style>

    .navbar {
        background: rgba(0, 0, 0, 0.8);
    }

    .navbar-header {
        color: #fff;
    }

    .navbar ul.nav li a {
        color: #fff;
        transition: all .5s;
    }

        .navbar ul.nav li a:hover {
            background: rgb(242, 120, 75);
            color: #fff;
            transition: all .5s;
        }

    .navbar-brand {
        text-transform: capitalize;
        color: #fff;
        position: relative;
        padding-left: 16px;
    }

        .navbar-brand:hover {
            color: #fff;
        }

        .navbar-brand::before {
            position: absolute;
            left: 2px;
            top: 19px;
            width: 10px;
            height: 10px;
            content: "";
            border-radius: 100%;
            background: #F2784B;
        }
</style>
</html>