UserApplication/Models/Messages.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace UserApplication.Models
{
    public class Messages
    {
        public int Id { get; set; }

        public string From { get; set; }

        public string To { get; set; }
        public string MessageBody { get; set; }
        public DateTime SendTime { get; set; }
        [ForeignKey("From")]
        public virtual ApplicationUser Sender { get; set; }
        [ForeignKey("To")]
        public virtual ApplicationUser Receiver { get; set; }
        public bool Vu { get; set; }
    }
}

UserApplication/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using UserApplication.Models;
using PagedList;
namespace UserApplication.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Messages
        public ActionResult Index()
        {
            var roleadmin = db.Roles.Where(r => r.Name == "Admin").FirstOrDefault();
            var userrole = db.Users.Where(u => u.Roles.Where(r => r.RoleId == roleadmin.Id).FirstOrDefault().RoleId == roleadmin.Id).FirstOrDefault();
            if (!User.IsInRole("Admin"))
                return RedirectToAction("ChatBox/" + userrole.Id);
            List<string> myids = new List<string>();
            var messages = db.Messages.Where(u => u.To == userrole.Id).OrderByDescending(o => o.SendTime).Select(s=>s.From).Distinct();
            myids.AddRange(messages);
            myids.Distinct();
            return View(myids.ToList());
        }
        public ActionResult CheckNewMessages(string id)
        {
            var messages = db.Messages.Where(u => u.From == id && u.Vu==false).ToList();
            foreach (var msg in messages)
            {
                msg.Vu = true;
                db.Entry(msg).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return View(messages);
        }
        public ActionResult ChatBox(string id)
        {
            var userid = User.Identity.GetUserId();
            if (id == null)
            {
                var roleadmin = db.Roles.Where(r => r.Name == "Admin").FirstOrDefault();
                var userrole = db.Users.Where(u => u.Roles.Where(r => r.RoleId == roleadmin.Id).FirstOrDefault().RoleId == roleadmin.Id).FirstOrDefault();
                id = userrole.Id;
                if (userrole.Id == User.Identity.GetUserId())
                    return RedirectToAction("Index");
            }

            Session["IdofMessage"] = id;
            var messages = db.Messages.Where(u => u.To == id && u.From == userid || u.To == userid && u.From == id).ToList();
            foreach (var msg in messages)
            {
                if (msg.To == User.Identity.GetUserId()) { 
                msg.Vu = true;
                db.Entry(msg).State = System.Data.Entity.EntityState.Modified;
                }
            }
            db.SaveChanges();
            return View(messages);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChatBox([Bind(Include = "MessageBody")]Messages message)
        {
            if (ModelState.IsValid)
            {
                var userid = User.Identity.GetUserId();
                Messages newmessage = new Messages();
                newmessage.From = User.Identity.GetUserId();
                newmessage.MessageBody = message.MessageBody;
                newmessage.To = (string)Session["IdofMessage"];

                newmessage.SendTime = DateTime.Now;
                db.Messages.Add(newmessage);
                db.SaveChanges();

                var usefullename = db.Users.Where(u => u.Id == newmessage.From).FirstOrDefault();
                string name;
                if (usefullename.FullName == null || usefullename.FullName == "")
                    name = usefullename.UserName;
                else
                    name = usefullename.UserName;
                Notifications newnotification = new Notifications();
                newnotification.Time = DateTime.Now;
                newnotification.NotificationUser = newmessage.To;
                newnotification.NotificationMessage = "New Messages from " + name;
                newnotification.Type = "message";
                db.Notifications.Add(newnotification);
                db.SaveChanges();


                return RedirectToAction("ChatBox/" + Session["IdofMessage"].ToString());
            }
            return View();
        }
        public ActionResult SendNewMessage(string SearchString, int? page)
        {
            if (!User.IsInRole("Admin"))
                return RedirectToAction("Index");
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var usersrole = db.Roles.Where(r => r.Name == "Users").FirstOrDefault();
            if (SearchString != null)
            {
                var users = db.Users.Where(r => r.Roles.Where(j => j.RoleId == usersrole.Id).FirstOrDefault().RoleId == usersrole.Id).Where(u => u.UserName.Contains(SearchString)).OrderByDescending(u => u.RegistrationDate).ToPagedList(pageNumber, pageSize);
                return View(users);
            }
            var userswithoutsearch = db.Users.Where(r => r.Roles.Where(j => j.RoleId == usersrole.Id).FirstOrDefault().RoleId == usersrole.Id).OrderByDescending(u => u.RegistrationDate).ToPagedList(pageNumber, pageSize);
            return View(userswithoutsearch);
        }
    }
}

UserApplication/Views/Messages/ChatBox.cshtml
@model IEnumerable<UserApplication.Models.Messages>
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "RealTime Chat Box";
    Layout = "~/Views/Shared/_LayoutLogined.cshtml";
    var userid = User.Identity.GetUserId();
}
<ol class="breadcrumb">
    @if (User.IsInRole("Admin"))
    {
        <li><a href="~/Dashboard/Index">Dashboard</a></li>
    }
    else
    {
        <li><a href="~/Users/Index">Dashboard</a></li>

    }    <li><a href="~/Messages/Index">Messages</a></li>
    <li class="active">RealTime Chat Box</li>
</ol>
<hr />
<div class="panel panel-info martop">
    <div class="panel-heading">
        <h3 class="panel-title">ChatBox</h3>
    </div>
    <div class="panel-body">
        @if (Model.Count() <= 0)
        {
            <div class="text-center">
                <span class="label label-default">Send Your First Message To this User Now !</span>
            </div>
        }
        <div class="messages">
            <ul id="AllMessages">
                @foreach (var msg in Model)
                {
                    if (msg.From == userid)
                    {
                        <li class="sent" id="lastmsg">
                            @if (msg.Sender.Profile == null)
                            {
                                <img src="~/UsersProfile/profile.png" alt="">
                            }
                            else
                            {
                                <img src="~/UsersProfile/@msg.Sender.Profile" alt="">
                            }

                            <p>
                                @msg.MessageBody
                                <br />
                                <span style="float:right;margin-right: 15px;color: #ff5353;">
                                   @if (msg.SendTime.Year == DateTime.Now.Year && msg.SendTime.Month == DateTime.Now.Month && msg.SendTime.Day == DateTime.Now.Day)
                                   {
                                       var elapsedminute = DateTime.Now - msg.SendTime;
                                       if (elapsedminute.TotalHours >= 1)
                                       {
                                        <span>@elapsedminute.TotalHours.ToString("0") hours ago</span>
                                       }
                                       else
                                       {
                                           if (elapsedminute.TotalMinutes.ToString("0") == "0")
                                           {
                                               if (elapsedminute.TotalSeconds.ToString("0") == "0")
                                               {
                                                <span>Just Now</span>
                                               }
                                               else
                                               {
                                                <span>@elapsedminute.TotalSeconds.ToString("0") secondes ago</span>
                                               }

                                           }
                                           else
                                           {

                                            <span>@elapsedminute.TotalMinutes.ToString("0") minutes ago</span>}

                                       }
                                   }
                                   else
                                   {
                                       if (msg.SendTime.Year == DateTime.Now.Year)
                                       {
                                        <span>@msg.SendTime.Day @msg.SendTime.ToString("MMMM") at @msg.SendTime.Hour.ToString("00"):@msg.SendTime.Minute.ToString("00")</span>
                                       }
                                       else
                                       {
                                        <span>@msg.SendTime</span>
                                       }
                                   }


                                    @if (msg.Vu)
                    {<span style="color: #fffa00;">Viewed</span>}
                                </span>
                            </p>
                        </li>

                    }
                    else
                    {
                        <li class="replies" id="lastmsg">
                            
                            @if (msg.Sender.Profile == null)
                            {
                                <img src="~/UsersProfile/profile.png" alt="">
                            }
                            else
                            {
                                <img src="~/UsersProfile/@msg.Sender.Profile" alt="">
                            }
                            
                            <p>
                                @msg.MessageBody<br />
                                <span style="float:right;margin-right: 15px;color: #ff5353;">
                                    @if (msg.SendTime.Year == DateTime.Now.Year && msg.SendTime.Month == DateTime.Now.Month && msg.SendTime.Day == DateTime.Now.Day)
                                    {
                                        var elapsedminute = DateTime.Now - msg.SendTime;
                                        if (elapsedminute.TotalHours >= 1)
                                        {
                                            <span>@elapsedminute.TotalHours.ToString("0") hours ago</span>
                                        }
                                        else
                                        {
                                            if (elapsedminute.TotalMinutes.ToString("0") == "0")
                                            {
                                                if (elapsedminute.TotalSeconds.ToString("0") == "0")
                                                {
                                                    <span>Just Now</span>
                                                }
                                                else
                                                {
                                                    <span>@elapsedminute.TotalSeconds.ToString("0") secondes ago</span>
                                                }

                                            }
                                            else
                                            {

                                                <span>@elapsedminute.TotalMinutes.ToString("0") minutes ago</span>}

                                        }
                                    }
                                    else
                                    {
                                        if (msg.SendTime.Year == DateTime.Now.Year)
                                        {
                                            <span>@msg.SendTime.Day @msg.SendTime.ToString("MMMM") at @msg.SendTime.Hour.ToString("00"):@msg.SendTime.Minute.ToString("00")</span>
                                        }
                                        else
                                        {
                                            <span>@msg.SendTime</span>
                                        }
                                    }

                                </span>
                            </p>


                        </li>
                    }
                }




            </ul>
        </div>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="message-input">
                <div class="wrap">
                    @Html.TextArea("MessageBody", new { @class = "textarea", @placeholder = "Saisissez votre message ...", @Required = "required" })
                    <!-- <textarea rows="1" placeholder="Saisissez votre message ..."></textarea>-->
                    <button class="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
                </div>
            </div>
        }
    </div>
</div>
<a href="~/Messages/Index" class="btn btn-warning">Retour</a> | @Html.ActionLink("Actualiser", null, null, new { @class = "btn btn-success" })
<br/>
<br />
<audio id="myAudio">
    <source src="~/Sounds/groupenotif.ogg" type="audio/ogg">
</audio>
<script>
    $(document).ready(function(){
        setInterval(function () {
            
            $.get("@Url.Action("CheckNewMessages/"+ Session["IdofMessage"].ToString(), "Messages")", function (data) {
                if (data.length > 10) {
                    document.getElementById('AllMessages').innerHTML = document.getElementById('AllMessages').innerHTML + data; scrolltolastmessage(); var x = document.getElementById("myAudio");x.play();
                }
            });
        }, 2500);
    });
    function scrolltolastmessage()
    {
        document.querySelectorAll("#lastmsg")[document.querySelectorAll("#lastmsg").length - 1].scrollIntoView();
    }
    scrolltolastmessage();
</script>
<style>
    .message-input .wrap button {
        float: right;
        border: none;
        width: 58px;
        padding: 12px 0;
        cursor: pointer;
        background: #32465a;
        color: #f5f5f5;
        height: 60px;
    }

        .message-input .wrap button:hover {
            background: #435f7a;
        }

    .message-input .wrap .textarea {
        padding: 15px 32px 16px 8px;
        height: 60px;
    }

    }

    .message-input .wrap .textarea:focus {
        outline: none;
    }

    .message-input {
        width: 100%;
        z-index: 99;
    }

        .message-input .wrap {
            position: relative;
        }

            .message-input .wrap .textarea {
                float: left;
                border: none;
                width: calc(100% - 60px);
                padding: 15px 32px 10px 8px;
                font-size: 0.8em;
                color: #32465a;
                border: 1px solid #808080;
                border-right: none;
            }

    .messages ul li {
        display: inline-block;
        clear: both;
        float: left;
        margin: 15px 15px 5px 15px;
        width: calc(100% - 25px);
        font-size: 0.9em;
    }

        .messages ul li.sent img {
            margin: 6px 8px 0 0;
        }

        .messages ul li.sent p {
            background: #435f7a;
            color: #f5f5f5;
        }

        .messages ul li.replies img {
            float: right;
            margin: 6px 0 0 8px;
        }

        .messages ul li.replies p {
            background: #f5f5f5;
            float: right;
        }

        .messages ul li img {
            width: 35px;
            border-radius: 50%;
            float: left;
        }

        .messages ul li p {
            display: inline-block;
            padding: 10px 15px;
            border-radius: 20px;
            max-width: 75%;
            line-height: 130%;
        }
</style>

UserApplication/Views/Messages/CheckNewMessages.cshtml
@model IEnumerable<UserApplication.Models.Messages>
@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "CheckNewMessages";
    Layout = "";
    var userid = User.Identity.GetUserId();
    UserApplication.Models.ApplicationDbContext db = new UserApplication.Models.ApplicationDbContext();
}

@if (Model != null)
{
    foreach (var msg in Model)
    {
        if (msg.From == userid)
        {
            <li class="sent" id="lastmsg">
                @if (msg.Sender.Profile == null)
                {
                    <img src="~/UsersProfile/profile.png" alt="">
                }
                else
                {
                    <img src="~/UsersProfile/@msg.Sender.Profile" alt="">
                }

                <p>
                    @msg.MessageBody<br />
                    <span style="float:right;margin-right: 15px;color: #ff5353;">
                        @if (msg.SendTime.Year == DateTime.Now.Year && msg.SendTime.Month == DateTime.Now.Month && msg.SendTime.Day == DateTime.Now.Day)
                        {
                            var elapsedminute = DateTime.Now - msg.SendTime;
                            if (elapsedminute.TotalHours >= 1)
                            {
                                <span>@elapsedminute.TotalHours.ToString("0") hours ago</span>
                            }
                            else
                            {
                                if (elapsedminute.TotalMinutes.ToString("0") == "0")
                                {
                                    if (elapsedminute.TotalSeconds.ToString("0") == "0")
                                    {
                                        <span>Just Now</span>
                                    }
                                    else
                                    {
                                        <span>@elapsedminute.TotalSeconds.ToString("0") secondes ago</span>
                                    }

                                }
                                else
                                {

                                    <span>@elapsedminute.TotalMinutes.ToString("0") minutes ago</span>}

                            }
                        }
                        else
                        {
                            if (msg.SendTime.Year == DateTime.Now.Year)
                            {
                                <span>@msg.SendTime.Day @msg.SendTime.ToString("MMMM") at @msg.SendTime.Hour.ToString("00"):@msg.SendTime.Minute.ToString("00")</span>
                            }
                            else
                            {
                                <span>@msg.SendTime</span>
                            }
                        }

                    </span>
                </p>
            </li>

        }
        else
        {
            <li class="replies" id="lastmsg">
                @if (msg.Sender.Profile == null)
                {
                    <img src="~/UsersProfile/profile.png" alt="">
                }
                else
                {
                    <img src="~/UsersProfile/@msg.Sender.Profile" alt="">
                }
                <p>
                    @msg.MessageBody<br />
                    <span style="float:right;margin-right: 15px;color: #ff5353;">
                        @if (msg.SendTime.Year == DateTime.Now.Year && msg.SendTime.Month == DateTime.Now.Month && msg.SendTime.Day == DateTime.Now.Day)
                        {
                            var elapsedminute = DateTime.Now - msg.SendTime;
                            if (elapsedminute.TotalHours >= 1)
                            {
                                <span>@elapsedminute.TotalHours.ToString("0") hours ago</span>
                            }
                            else
                            {
                                if (elapsedminute.TotalMinutes.ToString("0") == "0")
                                {
                                    if (elapsedminute.TotalSeconds.ToString("0") == "0")
                                    {
                                        <span>Just Now</span>
                                    }
                                    else
                                    {
                                        <span>@elapsedminute.TotalSeconds.ToString("0") secondes ago</span>
                                    }

                                }
                                else
                                {

                                    <span>@elapsedminute.TotalMinutes.ToString("0") minutes ago</span>}

                            }
                        }
                        else
                        {
                            if (msg.SendTime.Year == DateTime.Now.Year)
                            {
                                <span>@msg.SendTime.Day @msg.SendTime.ToString("MMMM") at @msg.SendTime.Hour.ToString("00"):@msg.SendTime.Minute.ToString("00")</span>
                            }
                            else
                            {
                                <span>@msg.SendTime</span>
                            }
                        }

                    </span>
                </p>

            </li>
        }
    }
}
else
{

}

UserApplication/Views/Messages/Index.cshtml
@model IEnumerable<string>
@using Microsoft.AspNet.Identity;
@{
    ViewBag.Title = "Messages List";
    Layout = "~/Views/Shared/_LayoutLogined.cshtml";
    UserApplication.Models.ApplicationDbContext db = new UserApplication.Models.ApplicationDbContext();
    var userid = User.Identity.GetUserId();
}
<ol class="breadcrumb">
    @if (User.IsInRole("Admin"))
    {
        <li><a href="~/Dashboard/Index">Dashboard</a></li>
    }
    else
    {
        <li><a href="~/Users/Index">Dashboard</a></li>

    }    <li class="active">Messages List</li>
</ol>
<hr />
<h2>Messages List</h2>
<hr/>
<p>
    <a href="~/Messages/SendNewMessage" class="btn btn-primary"><i class='fa fa-pencil-square-o'></i> Send new message</a>
</p>
<div class="text-center"><span class="label label-info">The sent messages will appear here after the recipient responds</span></div>
<br/>
<table class="table table-bordered table-striped table-hover">
    <tr>
        <th>
            Username
        </th>
        <th>
            Last Message
        </th>
        <th>
            Date
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            
            
            @if (db.Messages.Where(u => u.To == userid && u.From==item && u.Vu == false).Count() > 0)
            {
                <b>@db.Users.Where(u => u.Id == item).FirstOrDefault().UserName <span class="badge">@db.Messages.Where(u => u.To == userid && u.From == item && u.Vu == false).Count()</span></b>
            }
            else
            {
                <span>@db.Users.Where(u => u.Id == item).FirstOrDefault().UserName</span>
            }
            
        </td>
        <td>@db.Messages.Where(u => u.To == item || u.From == item).OrderByDescending(o => o.SendTime).FirstOrDefault().MessageBody</td>
        <td>
        @{ var msg = db.Messages.Where(u => u.To == item || u.From == item).OrderByDescending(o => o.SendTime).FirstOrDefault().SendTime;}
        @if (msg.Year == DateTime.Now.Year && msg.Month == DateTime.Now.Month && msg.Day == DateTime.Now.Day)
        {
                var elapsedminute = DateTime.Now - msg;
                if (elapsedminute.TotalHours >= 1)
                {
                <span>@elapsedminute Hours ago</span>
            }
            else
            {
                if (elapsedminute.TotalMinutes.ToString("0") == "0")
                {
                    if (elapsedminute.TotalSeconds.ToString("0") == "0")
                    {
                        <span>Just Now</span>
                    }
                    else
                    {
                        <span>@elapsedminute.TotalSeconds.ToString("0") secondes ago</span>
                    }

                }
                else
                {

                    <span>@elapsedminute.TotalMinutes.ToString("0") minutes ago</span>}

            }
        }
        else
        {
            if (msg.Year == DateTime.Now.Year)
            {
                <span>@msg.Day @msg.ToString("MMMM") at @msg.Hour.ToString("00"):@msg.Minute.ToString("00")</span>
            }
            else
            {
                <span>@msg</span>
            }
        }
        </td>
        <td><a href="~/Messages/Chatbox/@item" class="btn dashbtn-circle dashbtn-warning"><i class="fa fa-comment"></i></a> </td>
    </tr>
}

</table>

UserApplication/Views/Messages/SendNewMessage.cshtml
@model IEnumerable<UserApplication.Models.ApplicationUser>

@{
    ViewBag.Title = "Send New Message";
    Layout = "~/Views/Shared/_LayoutLogined.cshtml";
}
<ol class="breadcrumb">
    @if (User.IsInRole("Admin"))
    {
        <li><a href="~/Dashboard/Index">Dashboard</a></li>
    }
    else
    {
        <li><a href="~/Users/Index">Dashboard</a></li>

    }    <li><a href="~/Messages/Index">Messages</a></li>
    <li class="active">Send Message</li>
</ol>
<hr />
<h2>Send New Message</h2>
<hr/>
@using (Html.BeginForm())
{
    <p>
        Find by Username: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
    </p>
}

<table class="table table-bordered table-hover table-striped">
    <tr>
        <th>
            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @if (item.Profile != null)
            {
            <img src="~/UsersProfile/@item.Profile" class="img-circle img-responsive"  style="width: 50px;height: 50px;"/>
            }
            else
            {
                <img src="~/UsersProfile/profile.png" class="img-circle img-responsive" style="width: 50px;height: 50px;"/>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            <a href="~/Messages/ChatBox/@item.Id" class="btn dashbtn-circle dashbtn-warning" title="Send Message"><i style="width:30px" class="fa fa-comment"></i></a>
        </td>
    </tr>
}

</table>